# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of LimeSurvey systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ limesurvey_identifier }}.service"
  register: limesurvey_service_stat

- name: Uninstall LimeSurvey systemd services and files
  when: limesurvey_service_stat.stat.exists | bool
  block:
    - name: Ensure LimeSurvey systemd service is stopped
      ansible.builtin.service:
        name: "{{ limesurvey_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure LimeSurvey systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ limesurvey_identifier }}.service"
        state: absent

    - name: Ensure LimeSurvey support files do not exist
      ansible.builtin.file:
        path: "{{ limesurvey_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure LimeSurvey local path for config files does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ limesurvey_config_path }}"
      register: limesurvey_config_path_deletion_result
      changed_when: limesurvey_config_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure LimeSurvey local path for plugin files does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ limesurvey_plugin_path }}"
      register: limesurvey_plugin_path_deletion_result
      changed_when: limesurvey_plugin_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure LimeSurvey local path for uploaded files does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ limesurvey_upload_path }}"
      register: limesurvey_upload_path_deletion_result
      changed_when: limesurvey_upload_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure LimeSurvey base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ limesurvey_base_path }}"
      register: limesurvey_base_path_deletion_result
      changed_when: limesurvey_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure LimeSurvey container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ limesurvey_container_network }}"
        state: absent
      register: limesurvey_network_deletion_result

    - name: Ensure LimeSurvey container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ limesurvey_container_network }}
      register: limesurvey_network_deletion_result
      changed_when: limesurvey_container_network in limesurvey_network_deletion_result.stdout

- name: Check existence of LimeSurvey local path for config files
  ansible.builtin.stat:
    path: "{{ limesurvey_config_path }}"
  register: limesurvey_config_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if LimeSurvey local config files remain
  when: limesurvey_config_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local LimeSurvey instance has been removed, some old data remains in `" + limesurvey_config_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of LimeSurvey local path for plugin files
  ansible.builtin.stat:
    path: "{{ limesurvey_plugin_path }}"
  register: limesurvey_plugin_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if LimeSurvey local plugin files remain
  when: limesurvey_plugin_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local LimeSurvey instance has been removed, some old data remains in `" + limesurvey_plugin_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of LimeSurvey local path for uploaded files
  ansible.builtin.stat:
    path: "{{ limesurvey_upload_path }}"
  register: limesurvey_upload_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if LimeSurvey local upload files remain
  when: limesurvey_upload_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local LimeSurvey instance has been removed, some old data remains in `" + limesurvey_upload_path + "`. Feel free to delete it."
        ]
      }}
